// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['WEB_FIREBASE_API_KEY']!,
        appId: dotenv.env['WEB_FIREBASE_APP_ID']!,
        messagingSenderId: dotenv.env['WEB_FIREBASE_MESSAGING_SENDER_ID']!,
        projectId: dotenv.env['WEB_FIREBASE_PROJECT_ID']!,
        authDomain: dotenv.env['WEB_FIREBASE_AUTH_DOMAIN'],
        storageBucket: dotenv.env['WEB_FIREBASE_STORAGE_BUCKET'],
        measurementId: dotenv.env['WEB_FIREBASE_MEASUREMENT_ID'],
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['ANDROID_FIREBASE_API_KEY']!,
        appId: dotenv.env['ANDROID_FIREBASE_APP_ID']!,
        messagingSenderId: dotenv.env['ANDROID_FIREBASE_MESSAGING_SENDER_ID']!,
        projectId: dotenv.env['ANDROID_FIREBASE_PROJECT_ID']!,
        storageBucket: dotenv.env['ANDROID_FIREBASE_STORAGE_BUCKET'],
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['IOS_FIREBASE_API_KEY']!,
        appId: dotenv.env['IOS_FIREBASE_APP_ID']!,
        messagingSenderId: dotenv.env['IOS_FIREBASE_MESSAGING_SENDER_ID']!,
        projectId: dotenv.env['IOS_FIREBASE_PROJECT_ID']!,
        storageBucket: dotenv.env['IOS_FIREBASE_STORAGE_BUCKET'],
        iosClientId: dotenv.env['IOS_GOOGLE_CLIENT_ID'],
        iosBundleId: dotenv.env['IOS_BUNDLE_ID'],
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['MACOS_FIREBASE_API_KEY']!,
        appId: dotenv.env['MACOS_FIREBASE_APP_ID']!,
        messagingSenderId: dotenv.env['MACOS_FIREBASE_MESSAGING_SENDER_ID']!,
        projectId: dotenv.env['MACOS_FIREBASE_PROJECT_ID']!,
        storageBucket: dotenv.env['MACOS_FIREBASE_STORAGE_BUCKET'],
        iosClientId: dotenv.env['MACOS_GOOGLE_CLIENT_ID'],
        iosBundleId: dotenv.env['MACOS_BUNDLE_ID'],
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['WINDOWS_FIREBASE_API_KEY']!,
        appId: dotenv.env['WINDOWS_FIREBASE_APP_ID']!,
        messagingSenderId: dotenv.env['WINDOWS_FIREBASE_MESSAGING_SENDER_ID']!,
        projectId: dotenv.env['WINDOWS_FIREBASE_PROJECT_ID']!,
        storageBucket: dotenv.env['WINDOWS_FIREBASE_STORAGE_BUCKET'],
      );
}
